index:
   path: /
   controller: Portfolier\Controller\PortfolierController::index

registration:
  path: /registration/
  controller: Portfolier\Controller\PortfolierController::registration

login:
  path: /login/
  controller: Portfolier\Controller\PortfolierController::login

logout:
  path: /logout/
  controller: Portfolier\Controller\PortfolierController::logout